version: '3'

# From : https://github.com/simplesteph/kafka-stack-docker-compose
# PLUS :
#  => To improve the development time we will use a local database

services:

    mysql:
      image: mysql:5.7
      volumes:
      - ./full-stack/mysql/current:/var/lib/mysql
      - ./full-stack/mysql/backup:/var/mysql/backups:delegated
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: kafka
        MYSQL_USER: ist
        MYSQL_PASSWORD: ist
      ports:
      - "3306:3306"